### ISSUE TITLE
WarsTeamMemberUnknownComponent needs update 

### ISSUE THREAD

**Issue by d3death** [clugh/coc-messages#3]
AllianceWarData has WarTeam which has which has WarTeamMembers which has WarsTeamMemberUnknownComponent. 

This is broken and needs update. its supposed to print name but prints something like following

```
"unknown_20": {
          "name": "0016fd640100000000......
```

**Comment by clugh** [comment]
This appears to no longer be used in AllianceWarData, and was removed in 84dcfc643da29ec082dc48c4a9764ab39711bd91.

**Comment by d3death** [comment]
AllianceWarData still seems to be missing something since it gets stuck while trying to decrypt. 

edit: i spoke too soon, i was having network problems. sorry.

**Comment by clugh** [comment]
It is working as expected on my end.  Do you feel comfortable DMing me some sample data on Twitter?

**Comment by d3death** [comment]
yea i edited my earlier comment, i was having issues, that said i did send you DM
