### ISSUE TITLE
versions with debug symbols

### ISSUE THREAD

**Issue by mark1229** [clugh/coc-messages#8]
Hi clugh, 

in another issue you said that there is an old version of Clash of Clans with symbols. 
Can you give me a hint where I could get this old version? I looked at the newest ~50 Android versions I could get my hands on but they are all stripped.

Also, is there a way to get in touch with you? I would like to talk about clash of clans and if possible then also contribute to your reversing and documentation efforts.

Kind regards,
Mark

**Comment by clugh** [comment]
From the `cocdp` [wiki](https://github.com/clanner/cocdp/wiki/Versions):

> APK versions 2.20 and 5.2 have debug symbols, which make them ideal targets for reverse engineering.

As for contact info, you can DM me on Twitter: [@clughCoC](https://twitter.com/clughcoc).

**Comment by mark1229** [comment]
Thanks!
